spring:
  application:
    name: manaus-air-quality-service

  datasource:
    url: jdbc:postgresql://localhost:5432/manaus_air_quality
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

telegram:
  bot:
    username: "Air_quality"  # Username obtido no @BotFather
    token: "${TELEGRAM_BOT_TOKEN}"# Passado via variável de ambiente ou direto para testes